# Site settings
title: Joe Kroese
description: >
  The personal website of Joe Kroese
baseurl: "https://joekroese.com" # the subpath of your site, e.g. /blog/
url: "https://joekroese.com" # the base hostname & protocol for your site
lang:                en_GB
image:               /public/profile.jpg
tagline:             Maths, Music and Film in Manchester


author:
  fullname: Joe Kroese
  github: joekroese
twitter: joekroese

social:
  name: Joe Kroese
  links:
    - https://twitter.com/joekroese
    - https://github.com/joekroese


# Permalinks
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/joekroese/joekroese.github.io
google_analytics:    UA-105799284-1

paginate:            1

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

plugins:
  - jekyll-sitemap
