# Permalinks
permalink:           pretty

# Basic website info
title:               Joe Kroese
tagline:             Math, Music and Film in Manchester
description:         The personal website of Joe Kroese
url:                 https://joekroese.com
baseurl:             "https://joekroese.com"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Joe Kroese
  url:               https://twitter.com/joekroese
  email:             joekroese@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/joekroese/joekroese.github.io
google_analytics:    UA-105799284-1
twitter:
  username: joekroese
github:              joekroese
paginate:            1

social:
  name: Joe Kroese
  links:
    - https://twitter.com/joekroese
    - https://github.com/joekroese


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
