---
title: Jo Kroese
timezone: UTC
description: The personal website of Jo Kroese, where I talk about data, design, stories,
  politics and play.
url: https://jokroese.com
baseurl: ''
lang: en_GB
image: "/assets/img/profile.jpg"
tagline: Data science, art and music in Amsterdam
author:
  fullname: Jo Kroese
  github: joekroese
  twitter: joekroese
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed
version: 1.0.0
github:
  repo: https://github.com/joekroese/joekroese.github.io
google_analytics: UA-61246528-2
paginate: 1
# plugins:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jekyll-gist
#   - jekyll-seo-tag

collections:
  posts:
    title: Posts
    output: true
  pages:
    output: true
  projects:
    title: Projects
    output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"