# Site settings
title: Joe Kroese
description: The personal website of Joe Kroese, a place of data, stories and play.
url: "https://joekroese.com" # the base hostname & protocol for your site
baseurl: "" 
lang:                en_GB
image:               /public/profile.jpg
tagline:             Data science, music and startups in Montreal


author:
  fullname: Joe Kroese
  github: joekroese
  twitter: joekroese

# Permalinks
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/joekroese/joekroese.github.io
google_analytics:    UA-105799284-1

paginate:            1

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
