---
title: Jo Kroese
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: The personal website of Jo Kroese, a place of data, stories, justice
  and play.
url: https://jokroese.com
baseurl: ''
lang: en_GB
image: "/public/profile.jpg"
tagline: Data science, music and startups in Montreal
author:
  fullname: Jo Kroese
  github: joekroese
  twitter: joekroese
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed
version: 1.0.0
github:
  repo: https://github.com/joekroese/joekroese.github.io
google_analytics: UA-105799284-1
paginate: 1
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
