# Permalinks
permalink:           pretty

# Setup
title:               joe kroese
tagline:             math, music and film in manchester
url:                 http://joekroese.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Joe Kroese
  url:               https://twitter.com/joekroese
  email:             joekroese@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/joekroese/joekroese.github.io
google_analytics:    UA-105799284-1
twitter:             joekroese
github:              joekroese

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
